### ISSUE TITLE
AMZod favorite places to eat 

### ISSUE THREAD

**Issue by AMZod** [githubteacher/everyone-121715#2]
Let's add a document using:
- [x] Create a branch
- [x] Add a new file
- [x] Commit my file
- [x] Open Pull Request
- [ ] Discuss
- [ ] Merge

**Comment by AMZod** [comment]
Let's add a document using:

- [ ] Create a branch
- [ ] Add a new file
- [ ] Commit my file
- [ ] Open Pull Request
- [ ] Merge

**Comment by watridge** [comment]
here is a comment from me
