### ISSUE TITLE
GithubTeacher favorite places to eat

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/everyone-121715#4]
Let's add a document using:
- [x] Create a branch
- [x] Add a new file
- [x] Commit my file
- [x] Open Pull Request
- [ ] Discuss
- [ ] Merge

@carolynshin do you have any specific recommendations?

**Comment by carolynshin** [comment]
@githubteacher, YES! You need to try [Kamdesh Afghan Kabab House](http://www.yelp.com/biz/kamdesh-afghan-kabab-house-oakland-2)! :fork_and_knife:
